name: ir_project
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.19.3 <3.0.0'

dependencies:
  cupertino_icons: ^1.0.5
  get: 4.6.5
  http: ^0.13.5
  shared_preferences: ^2.0.18
  flutter_screenutil: ^5.7.0
  dartz: ^0.10.1
  flutter_svg: ^2.0.4
  shimmer: ^2.0.0
  awesome_dialog: ^3.0.2
  smooth_page_indicator: ^1.0.1
  lottie: ^2.3.0
  google_maps_flutter: ^2.2.5
  flutter_polyline_points: ^1.0.0
  geocoding: ^2.1.0
  location: ^4.4.0
  pull_to_refresh: ^2.0.0
  image_picker: ^0.8.7
  timeline_tile: ^2.0.0
  flutter: 
    sdk: flutter

dev_dependencies: 
  flutter_lints: ^2.0.0
  flutter_test: 
    sdk: flutter

flutter: 
  uses-material-design: true

  assets:
    - assets/
    - assets/icons/
    - assets/images/
